trigger:
- main

variables:
  imageName: 'flask-crypto-app'
  acrName: 'flaskacr123rd0804'
  acrLoginServer: 'flaskacr123rd0804.azurecr.io'
  tag: 'v1'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'

- script: |
    echo "Building Docker image..."
    docker build -t $(acrLoginServer)/$(imageName):$(tag) .
  displayName: 'Build Docker Image'

- script: |
    echo "Logging in to ACR..."
    echo $(ACR_PASSWORD) | docker login $(acrLoginServer) -u $(ACR_USERNAME) --password-stdin
  displayName: 'Login to ACR'

- script: |
    echo "Pushing image to ACR..."
    docker push $(acrLoginServer)/$(imageName):$(tag)
  displayName: 'Push Docker Image'
