name: Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/azure_key.pem
        chmod 600 ~/.ssh/azure_key.pem

    - name: Add Azure VM to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/azure_key.pem azureuser@${{ secrets.AZURE_HOST }} << 'EOF'
          cd flask/flask-crypto-app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python app.py > app.log 2>&1 &
        EOF
